- name: Configure git
  run: |
    git config --global user.name wahabu
    git config --global user.email ritscg2hibo@gmail.com

- name: Commit and push
  run: |
    git add .
    git commit -m "Update 3D Contrib using github-actions[bot]"
    git push
  env:
    GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
