name: GitHub-Profile-3D-Contrib
on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: '0 03 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Authenticate with GitHub
        run: git config --global user.token ${{ secrets.ACTIONS_ACCESS }}
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python ./bin/change-border.py profile-3d-contrib/profile-night-rainbow.svg profile-3d-contrib/profile-night-rainbow-with-border.svg

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Commit message"
          git push
        env:
          GIT_AUTHOR_TOKEN: ${{ secrets.ACTIONS_ACCESS }}
